version: "3.8"
services:
  postgres:
    image: postgres:15.2-alpine
    environment:
      - POSTGRES_USER=olegdjur
      - POSTGRES_PASSWORD=qwerty
      - POSTGRES_DB=auth_svc
    ports:
      - "5432:5432"
    networks:
      - app

  api:
    build: ./services/gateway/
 
    ports:
      - "3000:3000"
    networks:
    - app

  auth:
    build: ./services/auth/

    ports:
      - "50051:50051"
    hostname: auth
    environment:
      - DB_URL=postgres://olegdjur:qwerty@postgres:5432/auth_svc
    restart: on-failure
    networks:
      - app

networks:
  app: